---
title: "Construcción indice, sin hacinamiento"
author: "Melina Schamberger"
date: "22/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*1.Cargo las librerias*
```{r}
library(tidyverse)
library(sf)
library(ggplot2)
library(viridis)
```

*2.Cargo los datos*
```{r}
EAH <- read.csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/direccion-general-de-estadisticas-y-censos/encuesta-anual-hogares/encuesta-anual-hogares-2019.csv")
```

*3.CARACTERTIZACION GENERAL*
```{r}
#Cantidad de encuestades por comuna
personasXcomuna <- EAH %>% 
                    group_by(comuna) %>% 
                    summarise(total = n())

#Distribucion por sexo
sexo <- table(EAH$sexo)
sexo <- prop.table(sexo)
sexo <- as.data.frame(sexo)

sexo_comuna <- EAH %>% 
                group_by(comuna, sexo) %>%
                summarise(total_sexo= n ())

total_comuna<- EAH %>% 
  group_by(comuna) %>%
  summarise(total = n ())

sexo_final <- total_comuna %>% 
              inner_join(sexo_comuna, "comuna")

sexo_final <- sexo_final %>% group_by(comuna, sexo) %>% 
                              summarise(porc = ((total_sexo/total)*100), 
                                        abs = total_sexo)
#Grafico distribución por sexo en la ciudad.
ggplot(sexo_final)+
  geom_col(aes(x=as.character(comuna), y=porc, fill=sexo))+
  scale_fill_manual(values = c("#eb8023", "#5d09ed"))+
  geom_hline(yintercept=50, linetype="dashed", color="red")+
  labs(fill = "Sexo", x = "Comuna", y = "")+
  scale_y_continuous(limits = c(0, 100),
                    breaks = seq(0, 100, by = 25), 
                    labels = sprintf("%.0f%%", seq(0,100, by = 25)))+
  theme_minimal()
             
#Frecuencia de personas que viven en villas de emergencia: el 88% de la poblacion no vive en villas de emergencia.
villas <- table(EAH$dominio)
view(villas)
villas <- as.data.frame(prop.table(villas))
#Distribucion de las villas
villas_comunas <- EAH %>% 
  group_by(comuna) %>%
        filter(dominio == "Villas de emergencia") %>% 
        summarise(total = n(),
                  porcentaje = round((total/1739)*100))

#Grafico distribución de villas
ggplot(villas_comunas)+
  geom_col(aes(x=reorder(as.character(comuna),porcentaje), y=porcentaje), width = 0.5)

```

*4. CONSTRUIMOS DIMENSIONES*
```{r}
Sumatoria<-EAH%>%group_by(id, comuna,dominio) %>% 
  summarise(Total_hogar = n(),
            Per_con_ingresos = sum(calidad_ingresos_lab == "Tuvo ingresos y declara monto" | 
                                   calidad_ingresos_lab == "Tuvo ingresos pero no declara monto", 
                                   na.rm = TRUE),
            Dependientes = Per_con_ingresos/Total_hogar,
            personas_sin_ingresos = sum(calidad_ingresos_totales == "No tuvo ingresos" | 
                                        calidad_ingresos_totales =="No corresponde"),
            Sin_ingresos = personas_sin_ingresos/Total_hogar,
            Cobertura_p = sum(afiliacion_salud == "Solo sistema publico"),
            Sin_cobertura = Cobertura_p/Total_hogar)%>% 
  mutate(grado_dependencia = if_else((Dependientes > 0 & Dependientes < 0.20), 
                                                  "Alta carga de dependencia por ocupado", 
                                                  "Dependencia no alta"),
         percepcion = if_else(Sin_ingresos == 1,
                                            "No perciben",
                                            "Perciben"),
         salud = if_else(Sin_cobertura == 1,
                                          "Salud hogar vulnerable",
                                          "No vulnerable"),
         dominio=if_else(dominio== "Resto de la Ciudad",0,
                         0.2))
```
**4.1 AGREGAMOS EDUCACION*
```{r}
#Me quedo con las personas mayores de 18
anos_educacion<-EAH %>%
                  select(c(id, comuna, edad, años_escolaridad)) %>% 
                  filter(edad >= 18)
head(anos_educacion)
anos_educacion$años_escolaridad<-as.numeric(anos_educacion$años_escolaridad)

#Calculo media de años de educación por hogar
anos_educacion <- anos_educacion%>%
                      group_by(id, comuna) %>%
                      summarise(educacion = mean(años_escolaridad))

Sumatoria<-Sumatoria%>%inner_join(anos_educacion, c("id", "comuna"))

```


*5.CALCULAMOS INDICES*
```{r}
Construccion_indice <-Sumatoria %>% 
  mutate(ind_dominio= dominio,
         ind_depend = if_else(grado_dependencia == "Alta carga de dependencia por ocupado",
                                                  0.25,
                                                  0.00),
         ind_ingresos = if_else(Sin_ingresos == 1,
                                              0.15,
                                              0.00),
         ind_salud = if_else(Sin_cobertura == 1,
                                              0.15,
                                              0.00),
         ind_edu = case_when(
           educacion < 7 ~ 0.25,
           educacion >= 7 & educacion < 12 ~ 0.10,
           educacion >= 12 ~ 0)
         )

Construccion_indice<-Construccion_indice[,c(1,2,15:19)]
write.csv(Construccion_indice, "IVS.csv", fileEncoding = "UTF-8")
```

*5.1 UNIFICAMOS*
```{r}
ivs<-Construccion_indice%>%
      mutate(ind_total=sum(c(ind_dominio,ind_depend,ind_ingresos, ind_salud,ind_edu)))

ivs_x_comuna<-ivs%>%group_by(comuna)%>%
  summarise(media=mean(ind_total, na.rm = TRUE),
            variacion=var(ind_total, na.rm = TRUE),
            desvio=sd(ind_total, na.rm = TRUE))

```

*6-MAPA*
```{r}
caba<-st_read("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/comunas/CABA_comunas.geojson")
caba <- caba%>%
          rename(comuna=COMUNAS)%>%
          select(comuna, geometry)
caba$comuna<-as.numeric(caba$comuna)
head(caba)

ivs_x_comuna$comuna <- as.numeric(ivs_x_comuna$comuna)
head(ivs_x_comuna)

ivs_x_comuna <-left_join(x=caba, y=ivs_x_comuna)
ivs_x_comuna<-ivs_x_comuna%>%
                            mutate(centroide=st_centroid(geometry))
#Mapeo
plot_media<-ggplot()+
  geom_sf(data=ivs_x_comuna, 
          aes(fill=media))+
  scale_fill_viridis_b()
plot_media

plot_sd<-ggplot()+
  geom_sf(data=ivs_x_comuna, 
          aes(fill=desvio))+
  scale_fill_viridis_b()
plot_sd
```